# Generated by Django 4.0.7 on 2022-09-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='portraiture',
            new_name='description',
        ),
    ]
